### PR TITLE
Swik 958 screen only css

### PR DESCRIPTION
**Pull request by schatzopoulos**
Brings functionality for screen reader descriptions CSS class that is only visible by the screen reader

### CODE REVIEW

**Comment by abijames** [comment]
@schatzopoulos this look fine but I can't test is properly until it is merged.

@ali1k are you ok for this to be merged?

**Comment by schatzopoulos** [comment]
@abijames I think you can test it by going to slidewiki-platform/custom_modules/custom-semantic-ui and then git pull and git checkout SWIK-958_ScreenOnlyCSS. This will change to the specific branch of the custom-semantic-ui repo, if I am not mistaken.

**Comment by abijames** [comment]
I tried that but the branch didn't show up in custom-semantic-ui submodule in my git client. will try again after the call

**Comment by abijames** [comment]
@schatzopoulos got this working and it working correctly so I am merging!

**Pull request merged**
